---
- name: Setup_wireguard_between_cloud
  hosts: cloud
  remote_user: root
  vars:
    privkey: "/etc/wireguard/host.key"
    pubkey: "/etc/wireguard/host.pub"
    peer_conf: "/etc/wireguard/peers.conf"
    host_conf: "/etc/wireguard/wgvpn0.conf"
    wg_listen_port: 51820

  tasks:
    - name: Install_wireguard
      community.general.pacman:
        name: wireguard-tools
        state: present

    - name: Create_private_key
      ansible.builtin.shell:
        creates: "{{ privkey }}"
        cmd: "(umask u=r,g=,o= ; /usr/bin/wg genkey > {{ privkey }})"

    - name: Fetch_public_key_as_var
      ansible.builtin.shell:
        cmd: "/usr/bin/wg pubkey < {{ privkey }}"
      register: pubkey_fetch_result

    - name: Save_public_key_as_fact
      ansible.builtin.set_fact:
        wg_pub_key: "{{ pubkey_fetch_result.stdout | trim }}"

    - name: Save_peer_conf
      ansible.builtin.template:
        src: templates/peer.conf.j2
        dest: "{{ peer_conf }}"
        mode: u=r,g=r,o=r
        owner: root
        group: root

    - name: Save_host_conf
      ansible.builtin.template:
        src: templates/wgvpn0.conf.j2
        dest: "{{ host_conf }}"
        mode: u=r,g=r,o=r
        owner: root
        group: root

    - name: Enable_on_startup
      ansible.builtin.systemd:
        name: wg-quick@wgvpn0
        enabled: true
        state: restarted
