---
- name: Clone_dotfiles  # noqa latest[git]
  ansible.builtin.git:
    repo: "https://github.com/gauravjuvekar/dotfiles.git"
    dest: "/home/{{ main_user }}/.dotfiles"
    version: "master"

- name: Install_dotfiles
  ansible.builtin.command:
    chdir: "/home/{{ main_user }}/.dotfiles"
    argv:
      - "/home/{{ main_user }}/.dotfiles/setup.sh"
    creates: "/home/{{ main_user }}/.bashrc"
