---
- name: Create_default_release_profile
  firefox_profile:
    state: present
  register: ff_profile

- name: Copy_user_prefs_js
  ansible.builtin.copy:
    src: firefox_user_prefs.js
    dest: "{{ ff_profile.profile_path }}/user.js"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0600'
