- name: Network
  ansible.builtin.import_tasks: network.yml

- name: Install_aur_builder
  ansible.builtin.import_tasks: aur_builder.yml

- name: Install_packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
    update_cache: true

- name: Install_aur_packages
  become: true
  become_user: "{{ aur_builder_username }}"
  kewlfft.aur.aur:
    use: "yay"
    name: "{{ aur_packages }}"
    state: present
    update_cache: true

- name: Enable_locales
  community.general.locale_gen:
    name: '{{ item }}'
    state: present
  loop:
    - 'en_US.UTF-8'
    - 'en_DK.UTF-8'

- name: Configure_locale
  ansible.builtin.copy:
    src: files/locale.conf
    dest: /etc/locale.conf
    mode: '0644'
    owner: root
    group: root

- name: Configure_dconf
  ansible.builtin.import_tasks: dconf.yml

- name: Configure_firefox
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.import_tasks: firefox.yml

- name: Enable_pcscd
  ansible.builtin.systemd:
    name: pcscd.socket
    enabled: true
    state: started

- name: Configure_syncthing
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.import_tasks: syncthing.yml

- name: Fuse_mounts
  ansible.builtin.lineinfile:
    path: "/etc/fuse.conf"
    insertafter: '^#user_allow_other'
    line: 'user_allow_other'

- name: User_mounts
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.import_tasks: mounts.yml

- name: User_autostart
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.import_tasks: autostart.yml

- name: User_dotfiles
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.import_tasks: dotfiles.yml

- name: User_vim
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.import_tasks: vim.yml
