- name: Install_aur_builder
  ansible.builtin.import_tasks: aur_builder.yml

- name: Install_packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
    update_cache: true

- name: Install_aur_packages
  become: true
  become_user: "{{ aur_builder_username }}"
  kewlfft.aur.aur:
    use: "yay"
    name: "{{ aur_packages }}"
    state: present
    update_cache: true
