- name: Install_aur_builder
  ansible.builtin.import_tasks: aur_builder.yml

- name: Install_packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
    update_cache: true

- name: Install_aur_packages
  become: true
  become_user: "{{ aur_builder_username }}"
  kewlfft.aur.aur:
    use: "yay"
    name: "{{ aur_packages }}"
    state: present
    update_cache: true

- name: Configure_in_dconf
  become: true
  become_user: "{{ main_user }}"
  block:
    - name: Static_dconf_kv_pairs
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ dconf_settings }}"

    - name: Cinnamon_panels_read
      community.general.dconf:
        key: "/org/cinnamon/panels-height"
        state: read
      register: cinnamon_panel_heights_px

    - name: Cinnamon_panels_write
      community.general.dconf:
        key: "/org/cinnamon/panels-height"
        value: "{{ cinnamon_panel_heights_px.value | cinnamon_array_str_value(value=25, key=None) }}"
        state: present
