---
- name: Clone_dotvim  # noqa latest[git]
  ansible.builtin.git:
    repo: "https://github.com/gauravjuvekar/dotvim.git"
    dest: "/home/{{ main_user }}/.vim"
    version: "master"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Install_vim
  ansible.builtin.command:
    chdir: "/home/{{ main_user }}/.vim"
    argv:
      - "/home/{{ main_user }}/.vim/install.sh"
    creates: "/home/{{ main_user }}/.config/nvim/init.vim"
